### ISSUE TITLE
Eclipse Marketplace Download URL returns 404

### ISSUE THREAD

**Issue by scoth** [helospark/SparkBuilderGenerator#16]
The eclipse market place has the spark builder generator listed as a plugin to install.  However when it tries to download the plugin the following URL returns a 404:

https://helospark.com/eclipse_plugin/SparkBuilderGeneratorPlugin/content.xml

Is it possible to bring up this plugin on the server again, and/or provide a different means to download the plugin.  ( Could you host it on github? ).  I suppose I could build it myself, but I am not that familiar with building eclipse plugins.

Apologies if this is type of issue is inappropriate, I am not aware of another means of contacting the plugin maintainer.

**Comment by helospark** [comment]
Hi Scoth,

The generated update site contains jar for the context file and it is still available:
https://helospark.com/eclipse_plugin/SparkBuilderGeneratorPlugin/content.jar

In the logs I cannot see many queries for context.xml, as far as I know Eclipse tries context.xml if it cannot find content.jar.

I guess I can unzip the jar content and make that available too, but it shouldn't be necessary. Which Eclipse version do you use?

**Comment by scoth** [comment]
I wonder if the problem is that it doesn't allow the specific server certificate you have.

**Comment by scoth** [comment]
I am using the new Oxygen (4.7) version of Eclipse.  I tried the ftp url and I get the following:

An error occurred during the org.eclipse.equinox.internal.p2.engine.phases.CheckTrust phase.
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.CheckTrust, operand=, action=).
Error reading signed content.
Exception in opening zip file: /home/shale/opt/eclipse-jee-oxygen-R-linux-gtk-x86_64/plugins/com.helospark.SparkBuilderGenerator_0.0.10.201704081131.jar

**Comment by helospark** [comment]
Very unusual.
Based on some Google search it seems like a common problem, caused by the jar file somehow (?) gets corrupted:
https://stackoverflow.com/questions/25094583/error-when-try-install-plugin
Seems like some manual deleting of jar/xml files could solve it.

Some other thoughs:
 - my plugin is unsigned, could you have some special classloader/something, that only allows signed plugins to be installed?
 - What happens, if you manually try to open the jar file as a zip
 - What is the error message when installing via marketplace, only that content.xml is returned 404. I rarely see some logs on downloads, that some downloads cannot redirect to https, causing continuous 302 status codes. Not sure, what can be the cause, maybe not trusted HTTPS certificates (?)
 - Can you install other plugins?

**Comment by scoth** [comment]
I was able to install the unsigned eclipse decompiler from the marketplace.  So unsigned content of some kind works.  

When I try to open it as a zipfile I get the following error:  

**unzip -l /home/shale/opt/eclipse-jee-oxygen-R-linux-gtk-x86_64/plugins/com.helospark.SparkBuilderGenerator_0.0.10.201704081131.jar**
Archive:  /home/shale/opt/eclipse-jee-oxygen-R-linux-gtk-x86_64/plugins/com.helospark.SparkBuilderGenerator_0.0.10.201704081131.jar
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/shale/opt/eclipse-jee-oxygen-R-linux-gtk-x86_64/plugins/com.helospark.SparkBuilderGenerator_0.0.10.201704081131.jar or
        /home/shale/opt/eclipse-jee-oxygen-R-linux-gtk-x86_64/plugins/com.helospark.SparkBuilderGenerator_0.0.10.201704081131.jar.zip, and cannot find /home/shale/opt/eclipse-jee-oxygen-R-linux-gtk-x86_64/plugins/com.helospark.SparkBuilderGenerator_0.0.10.201704081131.jar.ZIP, period.

This is the error I get from the marketplace.  You pointed out that it could download the .jar.  I wonder if it is trying to get the content.xml first?:

Unable to read repository at https://helospark.com/eclipse_plugin/SparkBuilderGeneratorPlugin/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by helospark** [comment]
Based on the exception about the marketplace download failure most likely it is caused by:
http://gnuarmeclipse.github.io/blog/2016/12/02/plugins-install-issue/
I'm using certificate from Let's Encrypt which was added to the Java certificate store in version 1.8.101, but it should be able to check the validity of the certificate with older Java versions, but seems like it was blocked by a firewall. I'm not entirely sure what was blocked without analyzing the traffic.

"I wonder if it is trying to get the content.xml first?"
In this case Eclipse does not do a single request to my server, but fail fast after checking the certificate and unable to verify it.

About the downloaded jar file, have you tried the suggested solution on StackOverflow? It really seems like it got corrupted.
```
$ md5sum com.helospark.SparkBuilderGenerator_0.0.10.201704081131.jar
a22f3ba546e0633d78f40ab15005eb6c  com.helospark.SparkBuilderGenerator_0.0.10.201704081131.jar
```

**Comment by helospark** [comment]
Hey Scoth!

Any update on this?

**Comment by scoth** [comment]
I was able to update my JDK just now.  I was running jdk1.8.0_60, and updating to jdk1.8.0_131 allowed me to install the plugin without problems.  Thanks for your help!
