### ISSUE TITLE
Select class to generate builder for

### ISSUE THREAD

**Issue by woko666** [helospark/SparkBuilderGenerator#32]
Hello,
it'd be great to be able to select a class to generate a builder for, instead of generating a builder for the main class. My use case is 

`public class Constants
{
   public class RoomInfo
   {
      ...
   }

   public class UnitInfo
   {
      ...
   }
}`

and I'd love to select which nested class to generate the builder for, similarly to the native "Source -> Generate constructor/etc. " menu items, which generate the constructor depending on  which class the cursor was in at the time of opening the menu.
I tried cloning the source and having a go at it myself, but I got a lot of build errors that Google is kinda unhelpful about, so I decided to open an issue instead.

**Comment by helospark** [comment]
Hi @woko666,

Thanks for reporting this.

About the compile issue, have you installed the PDE (plugin development environment) plugin in your Eclipse? If you have not checked, please check [CONTRIBUTING.md](https://github.com/helospark/SparkBuilderGenerator/blob/master/CONTRIBUTING.md), I have tried to include the necessary information to import the project (but I could have missed out something).

About the issue: Nested classes are already supported by the builder generator, but nonstatic nested classes are [filtered out from the possible candidates](https://github.com/helospark/SparkBuilderGenerator/blob/4114eb410cb2999713c26bfb674bde504d8c9e14/SparkBuilderGeneratorPlugin/src/com/helospark/spark/builder/handlers/codegenerator/component/helper/IsTypeApplicableForBuilderGenerationPredicate.java#L22), because nonstatic nested classes cannot contain [static methods or static classes](https://stackoverflow.com/questions/975134/why-cant-we-have-static-method-in-a-non-static-inner-class), the builder generated (at the moment) would not compile, since
`public static final class Builder` and `public static Builder builder()` would both be syntactically incorrect in a nonstatic nested class.

This would make creating a new Builder instance a bit syntactically awkward, as I have highlighted in [this comment](https://github.com/helospark/SparkBuilderGenerator/issues/10#issuecomment-290177098).

If you would use static inner classes the builder is generated at the cursor position (if the "always generate builder to first (top level) class" setting is not set (which is the default)).

I can see ways to change the generated builder to work, but I'm curious about your opinion, how do you envision the builder in that case. Could you attach an example builder?

**Comment by woko666** [comment]
Hi @helospark ,
thanks for the explanation! That was indeed the snag, changing the nested classes to static fixes it for me. I'm using the Constants class to export all of the nested classes with associated data to C#/Java to have the same data on client/server, and the builders really make it much more readable, as the latest project uses rather more complex data structures that I'm used to.

As for the build error, I've managed to fix it as well. The issue was importing the project into an existing workspace, when I created a new one & imported it works like a charm.

Thanks for your great work and have a good one!
